on:
  push:
    branchs:
      - test2

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Create comments
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        URL: ${{ github.event.pull_request.comments_url }}
        GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

      run: |
        npm install htmllint-cli
        htmllint init
        pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        pull_number=1
        export GOPATH=$HOME/go
        export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
        go get -v github.com/syui/xq
        #url=${{ secrets.WEBHOOK_URL }}
        url_arch="https://www.archlinux.org/feeds/news/"
        url_archjp="https://www.archlinux.jp/feeds/news.xml"
        xml=index.xml
        xmljp=news.xml
        curl -sL $url_arch -o $xml
        curl -sLO $url_archjp
        link=`xq l l $xml`
        link=${link%*/}
        link=${link##*/}
        linkjp=`xq l l $xmljp`
        linkjp=${linkjp%*/}
        linkjp=${linkjp##*/}
        if [ "${link}" = "${linkjp}" ];then
          echo ok `xq l l $xmljp`
          exit
        fi
        title=`xq l title $xml`
        #title_ja=`curl -L -d "{\"txt\":\"$title\"}" $url`
        date_xml=`date --date="$(xq p $xml)" +"%Y-%m-%d" -u`
        body=`xq l description $xml|tr -d '\n'|sed -e 's/<[^>]*>//g' -e 's/\*//g'`
        #body_ja=`curl -L -d "{\"txt\":\"$body\"}" $url|sed 's/&#39;//g'`
        author=`xq $xml | jq -r ".[0].author.name"`

        up_xml=${date_xml}
        p=p.json
        URL=https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${pull_number}/comments
        curl -H "Authorization: token ${GITHUB_TOKEN}" \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${pull_number}/files > $p
        cat $p | jq -r ".[]|select(.filename == \"views/news/index.sql\")"|jq -r ".blob_url"
        check=`cat $p | jq -r ".[]|select(.filename == \"views/news/index.sql\")"`
        if [ -n "$check" ];then
          body_c="> ${link}\n${title}\n${date_xml}\n${up_xml}\n${author}"
          gh_url=`echo $check | jq -r ".blob_url"`"#L17-L23"
          raw_url=`echo $check | jq -r ".raw_url"`
          curl -X POST \
             -H "Authorization: token ${GITHUB_TOKEN}" \
             -d "{\"body\": \"${gh_url}\n\n${body_c}\"}" \
             ${URL}
        fi
        cat $p | jq -r ".[]|select(.filename == \"views/news/${link}.html\")"|jq -r ".blob_url"
        check=`cat $p | jq -r ".[]|select(.filename == \"views/news/${link}.html\")"`
        if [ -n "$check" ];then
          line=`echo $check | jq -r ".additions"`
          gh_url=`echo $check | jq -r ".blob_url"`"#L1-L${line}"
          raw_url=`echo $check | jq -r ".raw_url"`
          curl -sLO $raw_url
          if ! htmllint *.html ;then
            curl -X POST \
               -H "Authorization: token ${GITHUB_TOKEN}" \
               -d "{\"body\": \"`htmllint *.html`\"}" \
               ${URL}
          fi
          curl -X POST \
             -H "Authorization: token ${GITHUB_TOKEN}" \
             -d "{\"body\": \"${gh_url}\n\n> ${body}\n\n$(xq l l $xml)\"}" \
             ${URL}
        fi
